baseURL = "https://rwbyg.club/"
languageCode = "en-us"
title = "/RWBYg/"
theme = "paperback"
publishDir = "docs"

[params]
# tagline to show beneath homepage h1
# default: undefined
#Tagline = "Hello, world!"

# number of posts to show on index
# default: 10
#HomepagePosts = 3

# default: undefined
GithubUsername = "RWBYg"
